version: 2
updates:
  # NPM dependencies for your Svelte + Vite project
  - package-ecosystem: "npm"
    directory: "/"  # Root directory of your project
    schedule:
      interval: "daily"  # Frequent updates to stay on top of vulnerabilities
    commit-message:
      prefix: "deps(svelte)"
      include: "scope"
    open-pull-requests-limit: 5  # Limit the number of open PRs
    labels:
      - "dependencies"
      - "svelte"
    assignees:
      - "kroonen"  # Automatically assigns PRs to you
    reviewers:
      - "kroonen"  # Automatically adds you as a reviewer
    rebase-strategy: "auto"  # Automatically rebase PRs if conflicts
    ignore:
      - dependency-name: "svelte"
        update-types: ["version-update:semver-major"]  # Avoid breaking changes
    pull-request-branch-name:
      separator: "_"

  # GitHub Actions dependencies (if you're using CI)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  # Less frequent updates for GitHub Actions
    commit-message:
      prefix: "ci(actions)"
    labels:
      - "ci"
    assignees:
      - "kroonen"
    rebase-strategy: "auto"

# Automerge configuration
automerge:
  enabled: true
  # Automerge minor or patch updates after you review them
  strategy: "auto"
  update-type: "version-update:semver-minor"
  reviewers: ["kroonen"]  # Requires your review before automerging
