version: 2
updates:
  # NPM dependencies (for your Svelte + Vite project)
  - package-ecosystem: "yarn"
    directory: "/" # Root directory of your project
    schedule:
      interval: "daily"  # Frequent updates to keep on top of vulnerabilities
    commit-message:
      prefix: "deps(svelte)"  # Clear commit prefix for easier identification
      include: "scope"
    open-pull-requests-limit: 20  # Prevent Dependabot from opening too many PRs at once
    labels:
      - "dependencies"
      - "svelte"  # Label for easy filtering of Svelte-related updates
    assignees:
      - "kroonen"  # Automatically assign the PRs to you
    reviewers:
      - "kroonen"  # You will review the updates manually
    rebase-strategy: "auto"  # Automatically rebase when PRs have conflicts
    ignore:
      - dependency-name: "svelte"
        update-types: ["version-update:semver-major"]  # Avoid breaking changes for major versions
    pull-request-branch-name:
      separator: "_"
  
  # GitHub Actions (for CI/CD updates)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(actions)"
    labels:
      - "ci"
    assignees:
      - "kroonen"
    rebase-strategy: "auto"

# Optional: Automerge rules for less interactive maintenance
automerge:
  # Auto-merge minor or patch updates after review to lighten the load
  - package-ecosystem: "npm"
    directory: "/"
    automerge-type: "pr"
    allowed-update-types:
      - "version-update:semver-minor"
      - "version-update:semver-patch"
    review-required: true
